### ISSUE TITLE
Question on location codes

### ISSUE THREAD

**Issue by aringler-usgs** [paudetseis/SplitPy#8]
Hello,  I am trying to run this on two different location codes at a single station.  However, when I make the database using `query_fdsn_stdb.py` I only get one location code.

e.g.,

```
   Station: ANMO
     Lon, Lat, Elev: -106.4572,  34.9459,   1.820
     Start Date: 2008-06-30 20:00:00
     End Date:   2020-07-24 16:07:27
     Status:     open
     Selected Channel: BH
     Locations:        --
    Warning: IU.ANMO already exists...Skip
```
However, ANMO currently doesn't have a -- location code sensor.  It has a 00 and 10.  

Thanks for your help.

**Comment by paudetseis** [comment]
Thanks for your note. This is an issue with StDb - @schaefferaj could you address it?

A workaround would be to manually edit the database using the edit_std.py script, edit the location code and you can also add one station (same station but different location code) to the database using append_stdb.py

**Comment by paudetseis** [comment]
Discussion moved to `StDb`: https://github.com/schaefferaj/StDb/issues/17
